# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86fdbd2135723e7972dee46259bd0e68c91f8af412e4f8dc3680693ca1bd112f8a34e8f297b40e378ab404f4a16f8fa3a117f6294d283a2705f7ce4502ea7782

test:
  secret_key_base: 988f81c607f55b8d164ed8b4a586d64f9467bb704dc555b9d53327eb6a2bc09858c27c5deffe191dbf2cb4bbe76c0280dee109968c58a03809203969ddf40419

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
